package com.abclonal.product.dao.mapper;

import com.abclonal.product.dao.entity.InventoryEntity;
import com.abclonal.product.dao.entity.InventoryEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InventoryEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated Sat Feb 14 15:31:47 CST 2026
     */
    long countByExample(InventoryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated Sat Feb 14 15:31:47 CST 2026
     */
    int deleteByExample(InventoryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated Sat Feb 14 15:31:47 CST 2026
     */
    int insert(InventoryEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated Sat Feb 14 15:31:47 CST 2026
     */
    int insertSelective(InventoryEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated Sat Feb 14 15:31:47 CST 2026
     */
    List<InventoryEntity> selectByExample(InventoryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated Sat Feb 14 15:31:47 CST 2026
     */
    int updateByExampleSelective(@Param("row") InventoryEntity row, @Param("example") InventoryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated Sat Feb 14 15:31:47 CST 2026
     */
    int updateByExample(@Param("row") InventoryEntity row, @Param("example") InventoryEntityExample example);
}