package com.abclonal.product.dao.mapper;

import com.abclonal.product.dao.entity.QrCodeEntity;
import com.abclonal.product.dao.entity.QrCodeEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrCodeEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_qrcode
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    long countByExample(QrCodeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_qrcode
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    int deleteByExample(QrCodeEntityExample example);
    int batchInsert(@Param("list") List<QrCodeEntity> list);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_qrcode
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_qrcode
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    int insert(QrCodeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_qrcode
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    int insertSelective(QrCodeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_qrcode
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    List<QrCodeEntity> selectByExampleWithBLOBs(QrCodeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_qrcode
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    List<QrCodeEntity> selectByExample(QrCodeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_qrcode
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    QrCodeEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_qrcode
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    int updateByExampleSelective(@Param("row") QrCodeEntity row, @Param("example") QrCodeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_qrcode
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    int updateByExampleWithBLOBs(@Param("row") QrCodeEntity row, @Param("example") QrCodeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_qrcode
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    int updateByExample(@Param("row") QrCodeEntity row, @Param("example") QrCodeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_qrcode
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    int updateByPrimaryKeySelective(QrCodeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_qrcode
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    int updateByPrimaryKeyWithBLOBs(QrCodeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_qrcode
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    int updateByPrimaryKey(QrCodeEntity row);
}