-- ========================================================-- WMS 系统 - 按钮权限增量脚本-- ========================================================
-- 说明：此脚本仅添加按钮权限（menu_type='F'），
--       如果菜单已存在，请先在菜单管理界面手动添加或删除重复数据后执行

-- ========================================================-- 1. 用户管理按钮权限（parent_id = 3）-- ========================================================
INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time) VALUES (1001, '用户查询', 3, 1, '', '', '1', '0', 'F', '0', '0', 'system:user:query', '#', 'system', NOW());INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time) VALUES (1002, '用户新增', 3, 2, '', '', '1', '0', 'F', '0', '0', 'system:user:add', '#', 'system', NOW());INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time) VALUES (1003, '用户修改', 3, 3, '', '', '1', '0', 'F', '0', '0', 'system:user:edit', '#', 'system', NOW());INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time) VALUES (1004, '用户删除', 3, 4, '', '', '1', '0', 'F', '0', '0', 'system:user:delete', '#', 'system', NOW());INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time) VALUES (1005, '用户导出', 3, 5, '', '', '1', '0', 'F', '0', '0', 'system:user:export', '#', 'system', NOW());
-- ========================================================-- 2. 角色管理按钮权限（parent_id = 4）-- ========================================================
INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time) VALUES (1010, '角色查询', 4, 1, '', '', '1', '0', 'F', '0', '0', 'system:role:query', '#', 'system', NOW());INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time) VALUES (1011, '角色新增', 4, 2, '', '', '1', '0', 'F', '0', '0', 'system:role:add', '#', 'system', NOW());INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time) VALUES (1012, '角色修改', 4, 3, '', '', '1', '0', 'F', '0', '0', 'system:role:edit', '#', 'system', NOW());INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time) VALUES (1013, '角色删除', 4, 4, '', '', '1', '0', 'F', '0', '0', 'system:role:delete', '#', 'system', NOW());INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time) VALUES (1014, '分配权限', 4, 5, '', '', '1', '0', 'F', '0', '0', 'system:role:assign', '#', 'system', NOW());
-- ========================================================-- 3. 部门管理按钮权限（parent_id = 5）-- ========================================================
INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time) VALUES (1020, '部门查询', 5, 1, '', '', '1', '0', 'F', '0', '0', 'system:dept:query', '#', 'system', NOW());INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time) VALUES (1021, '部门新增', 5, 2, '', '', '1', '0', 'F', '0', '0', 'system:dept:add', '#', 'system', NOW());INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time) VALUES (1022, '部门修改', 5, 3, '', '', '1', '0', 'F', '0', '0', 'system:dept:edit', '#', 'system', NOW());INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time) VALUES (1023, '部门删除', 5, 4, '', '', '1', '0', 'F', '0', '0', 'system:dept:delete', '#', 'system', NOW());
-- ========================================================-- 4. 菜单管理按钮权限（parent_id = 6）-- ========================================================
INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time) VALUES (1030, '菜单查询', 6, 1, '', '', '1', '0', 'F', '0', '0', 'system:menu:query', '#', 'system', NOW());INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time) VALUES (1031, '菜单新增', 6, 2, '', '', '1', '0', 'F', '0', '0', 'system:menu:add', '#', 'system', NOW());INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time) VALUES (1032, '菜单修改', 6, 3, '', '', '1', '0', 'F', '0', '0', 'system:menu:edit', '#', 'system', NOW());INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time) VALUES (1033, '菜单删除', 6, 4, '', '', '1', '0', 'F', '0', '0', 'system:menu:delete', '#', 'system', NOW());
-- ========================================================-- 5. 字典管理按钮权限（parent_id = 7）-- ========================================================
INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time) VALUES (1040, '字典查询', 7, 1, '', '', '1', '0', 'F', '0', '0', 'system:dict:query', '#', 'system', NOW());INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time) VALUES (1041, '字典新增', 7, 2, '', '', '1', '0', 'F', '0', '0', 'system:dict:add', '#', 'system', NOW());INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time) VALUES (1042, '字典修改', 7, 3, '', '', '1', '0', 'F', '0', '0', 'system:dict:edit', '#', 'system', NOW());INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time) VALUES (1043, '字典删除', 7, 4, '', '', '1', '0', 'F', '0', '0', 'system:dict:delete', '#', 'system', NOW());INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time) VALUES (1044, '字典导出', 7, 5, '', '', '1', '0', 'F', '0', '0', 'system:dict:export', '#', 'system', NOW());
-- ========================================================-- 6. 为admin角色（role_id=1）分配所有按钮权限-- ========================================================
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1001);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1002);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1003);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1004);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1005);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1010);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1011);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1012);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1013);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1014);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1020);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1021);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1022);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1023);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1030);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1031);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1032);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1033);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1040);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1041);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1042);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1043);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1044);

-- ========================================================-- 按钮权限添加完成-- ========================================================