package com.abclonal.product.dao.entity;

import java.util.Date;
import lombok.Data;

@Data
public class InventoryEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.id
     *
     * @mbg.generated Sat Feb 14 15:31:47 CST 2026
     */
     private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.name
     *
     * @mbg.generated Sat Feb 14 15:31:47 CST 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.createBy
     *
     * @mbg.generated Sat Feb 14 15:31:47 CST 2026
     */
    private String createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.createTime
     *
     * @mbg.generated Sat Feb 14 15:31:47 CST 2026
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.updateBy
     *
     * @mbg.generated Sat Feb 14 15:31:47 CST 2026
     */
    private String updateby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.updateTime
     *
     * @mbg.generated Sat Feb 14 15:31:47 CST 2026
     */
    private Date updatetime;
}