package com.abclonal.product.dao.entity;

import java.util.Date;
import lombok.Data;

@Data
public class QrCodeEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_qrcode.id
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    public Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_qrcode.qrcode
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    public String qrcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_qrcode.catalogno
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    public String catalogno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_qrcode.productname
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    public String productname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_qrcode.batchid
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    public String batchid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_qrcode.size
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    public String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_qrcode.unit
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    public String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_qrcode.create_by
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    public String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_qrcode.create_time
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    public Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_qrcode.update_by
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    public String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_qrcode.update_time
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    public Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_qrcode.is_deleted
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    public Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_qrcode.remark
     *
     * @mbg.generated Wed Feb 25 15:39:38 CST 2026
     */
    public String remark;
}